In [2]:
import torch
import PIL
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import cv2
import json
import csv

In [7]:
myFile1 = pd.read_csv('/home/ubuntu/RecycleCloth/Datasets/DeepFashion2/img_info_dataframes/train.csv')
myFile1

,path,segmentation,landmarks,b_box,category_id,category_name,scale,viewpoint,occlusion,zoom_in,img_height,img_width
0,/kaggle/input/deepfashion2-original-with-dataf...,"[[360, 172, 364, 166, 371, 163, 325, 168, 299,...","[387, 176, 1, 371, 163, 1, 364, 166, 1, 360, 1...","[227, 155, 442, 381]",4,long sleeve outwear,2,2,2,1,640,640
1,/kaggle/input/deepfashion2-original-with-dataf...,"[[381, 306, 334, 289, 297, 266, 261, 350, 225,...","[297, 266, 1, 334, 289, 1, 381, 306, 1, 261, 3...","[209, 263, 387, 539]",8,trousers,2,2,2,1,640,640
2,/kaggle/input/deepfashion2-original-with-dataf...,"[[320, 33, 309, 86, 247, 102, 183, 78, 172, 27...","[241, 45, 2, 172, 27, 2, 183, 78, 2, 247, 102,...","[6, 17, 460, 341]",1,short sleeve top,3,1,1,1,631,468
3,/kaggle/input/deepfashion2-original-with-dataf...,"[[150, 285, 249, 302, 350, 270, 464, 396, 464,...","[150, 285, 2, 249, 302, 2, 350, 270, 2, 0, 0, ...","[0, 263, 465, 630]",9,skirt,3,1,1,3,631,468
4,/kaggle/input/deepfashion2-original-with-dataf...,"[[351, 246, 353, 277, 325, 297, 279, 302, 242,...","[298, 270, 1, 242, 287, 2, 279, 302, 2, 325, 2...","[178, 182, 695, 800]",10,short sleeve dress,3,2,2,1,926,750
...,...,...,...,...,...,...,...,...,...,...,...,...
312181,/kaggle/input/deepfashion2-original-with-dataf...,"[[471, 456, 436, 503, 386, 553, 338, 519, 314,...","[388, 456, 1, 314, 458, 1, 338, 519, 1, 386, 5...","[112, 448, 711, 1039]",2,long sleeve top,2,2,2,1,1141,800
312182,/kaggle/input/deepfashion2-original-with-dataf...,"[[528, 863, 410, 868, 299, 861, 296, 1003, 320...","[299, 861, 1, 410, 868, 1, 528, 863, 1, 296, 1...","[286, 855, 542, 1140]",8,trousers,1,2,2,3,1141,800
312183,/kaggle/input/deepfashion2-original-with-dataf...,"[[214.0, 269.0, 226.0, 297.0, 248.0, 357.0, 25...","[304, 301, 1, 256, 320, 2, 281, 318, 2, 308, 3...","[191, 168, 495, 783]",13,sling dress,2,2,1,1,960,640
312184,/kaggle/input/deepfashion2-original-with-dataf...,"[[212.94, 211.43, 219.97, 202.76, 235.84, 192....","[274, 194, 1, 234, 202, 2, 254, 237, 2, 290, 2...","[155, 164, 452, 440]",1,short sleeve top,2,2,2,1,960,640
312185,/kaggle/input/deepfashion2-original-with-dataf...,"[[711, 98, 500, 66, 327, 63, 300, 222, 283, 35...","[327, 63, 1, 500, 66, 1, 711, 98, 1, 300, 222,...","[259, 52, 725, 488]",7,shorts,2,3,2,1,660,880

In [6]:
myFile2 = pd.read_json('/home/ubuntu/RecycleCloth/Datasets/DeepFashion2/deepfashion2_original_images/train/annos/000001.json').drop(columns='pair_id').drop(columns='source')
myFile2

,item2,item1
segmentation,"[[460, 438, 374, 484, 251, 520, 269, 586, 298,...","[[257, 35, 261, 89, 228, 123, 137, 103, 45, 91..."
scale,2,3
viewpoint,2,2
zoom_in,3,2
landmarks,"[251, 520, 1, 374, 484, 1, 460, 438, 1, 269, 5...","[182, 54, 1, 45, 91, 1, 137, 103, 1, 228, 123,..."
style,0,1
bounding_box,"[249, 423, 466, 623]","[0, 29, 466, 622]"
category_id,8,1
occlusion,2,2
category_name,trousers,short sleeve top

In [5]:
#blabla = pd.read_json('/home/ubuntu/RecycleCloth/Datasets/DeepFashion2/deepfashion2_original_images/train/annos/000001.json')

with open('/home/ubuntu/RecycleCloth/Datasets/DeepFashion2/deepfashion2_original_images/train/annos/000001.json') as f:
    data = json.load(f)
# data['item1']
# data['item2']

ann = list(data['item1'].keys())
ann[6]

data['item1']['segmentation']

[[257,
  35,
  261,
  89,
  228,
  123,
  137,
  103,
  45,
  91,
  1,
  176,
  0,
  332,
  47,
  447,
  151,
  401,
  141,
  366,
  129,
  328,
  141,
  364,
  219,
  485,
  274,
  603,
  401,
  590,
  467,
  502,
  442,
  336,
  369,
  195,
  348,
  138,
  363,
  163,
  372,
  197,
  433,
  137,
  396,
  92,
  341,
  35,
  257,
  35],
 [1, 176, 0, 332, 47, 447, 151, 401, 141, 366, 129, 328, 1, 176],
 [348, 138, 363, 163, 372, 197, 433, 137, 396, 92, 341, 35, 348, 138]]

In [ ]:
import json

with open('/home/ubuntu/RecycleCloth/Datasets/DeepFashion2/deepfashion2_original_images/validation/json_for_validation/keypoints_val_information.json') as json_data:
    myFile4 = json.load(json_data)

myFile4.pop('info') #Remove empty keys
myFile4.pop('licenses') #Remove empty keys
myFile4.pop('annotations') #Remove empty keys

image_data_temp = pd.DataFrame(myFile4['images']).drop(columns=['date_captured', 'coco_url', 'flickr_url']).reset_index().set_index('id')
category_temp = pd.DataFrame(myFile4['categories']).drop(columns=['skeleton', 'supercategory']).reset_index().set_index('id')

[]

In [ ]:
image_data_temp

       index  width  license   file_name  height
id
1          0    468        0  000001.jpg     624
2          1    468        0  000002.jpg     624
3          2    468        0  000003.jpg     628
4          3    468        0  000004.jpg     632
5          4    468        0  000005.jpg     624
...      ...    ...      ...         ...     ...
32149  32148    880        0  032149.jpg    1321
32150  32149    880        0  032150.jpg    1321
32151  32150    880        0  032151.jpg    1321
32152  32151    880        0  032152.jpg    1321
32153  32152    468        0  032153.jpg     702

[32153 rows x 5 columns]

In [69]:
category_temp['keypoints']

id
1     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
2     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
3     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
4     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
5     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
6     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
7     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
8     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
9     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
10    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
11    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
12    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
13    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
Name: keypoints, dtype: object

In [75]:
with open('/home/ubuntu/RecycleCloth/Datasets/DeepFashion2/deepfashion2_original_images/validation/json_for_validation/retrieval_val_consumer_information.json') as json_data:
    myFile5 = json.load(json_data)


myFile5.pop('info') #Remove empty keys
myFile5.pop('licenses') #Remove empty keys
myFile5.pop('annotations') #Remove empty keys

image_data_temp = pd.DataFrame(myFile5['images']).drop(columns=['date_captured', 'coco_url', 'flickr_url']).reset_index().set_index('id')
category_temp = pd.DataFrame(myFile5['categories']).drop(columns=['skeleton', 'supercategory']).reset_index().set_index('id')

In [77]:
image_data_temp

       index  width  license   file_name  height
id
1          0    468        0  000001.jpg     624
2          1    468        0  000002.jpg     624
3          2    468        0  000003.jpg     628
4          3    468        0  000004.jpg     632
5          4    468        0  000005.jpg     624
...      ...    ...      ...         ...     ...
10840  10839    468        0  010840.jpg     624
10841  10840    468        0  010841.jpg     832
10842  10841    468        0  010842.jpg     624
10843  10842    468        0  010843.jpg     624
10844  10843    468        0  010844.jpg     624

[10844 rows x 5 columns]